[package]
name = "wita_inner_window"
version = "0.1.0"
authors = ["LNSEAB <691752+LNSEAB@users.noreply.github.com>"]
edition = "2018"

[dependencies]
wita = { path = "../.." }
windows = "0.6.0"
anyhow = "1.0.39"

[build-dependencies]
windows = "0.6.0"
