fn main() {
    windows::build!(
        windows::win32::windows_and_messaging::*,
        windows::win32::hi_dpi::*,
        windows::win32::gdi::{
            MonitorFromPoint,
            GetMonitorInfoW,
            EnumDisplayMonitors,
            BeginPaint,
            EndPaint,
            GetStockObject,
            RedrawWindow,
        },
        windows::win32::keyboard_and_mouse_input::*,
        windows::win32::system_services::{
            BOOL,
            HINSTANCE,
            LocalFree,
            GetModuleHandleW,
        },
        windows::win32::display_devices::{
            POINT,
            RECT,
        },
        windows::win32::debug::{
            FormatMessageW,
            GetLastError,
            FORMAT_MESSAGE_OPTIONS,
        },
        windows::win32::intl::*,
        windows::win32::shell::{
            DragAcceptFiles,
            DragQueryFileW,
            DragQueryPoint,
            DragFinish,
        },
        windows::win32::menus_and_resources::{
            HICON,
        },
        windows::win32::controls::{
            ImageListLoadImage_uFlags,
            WM_MOUSELEAVE,
        },
        windows::win32::windows_programming::{
            CloseHandle,
        },
        windows::win32::file_system::{
            CreateFileW,
        },
        windows::win32::hid::*,
    );
}
