[package]
name = "icon_resource"
version = "0.1.0"
authors = ["LNSEAB <691752+LNSEAB@users.noreply.github.com>"]
edition = "2018"

[dependencies]
wita = { path = "../.." }

[build-dependencies]
embed-resource = "1.4.1"

[dev-dependencies]
anyhow = "1.0.38"